=== epilot-dev/docs/static/schemas/calendar_event-jsonschema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_schema",
    "calendar",
    "event_type",
    "start_time",
    "end_time",
    "source_type"
  ],
  "properties": {
    "_schema": {
      "readOnly": true,
      "type": "string",
      "pattern": "^[a-zA-Z0-9_-]+$",
      "example": "calendar_event",
      "description": "URL-friendly identifier for the entity schema"
    },
    "_id": {
      "readOnly": true,
      "type": "string",
      "format": "uuid",
      "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "description": "Unique identifier for the entity"
    },
    "_org": {
      "type": "string",
      "description": "Organization Id the entity belongs to",
      "readOnly": true,
      "example": "123"
    },
    "_title": {
      "readOnly": true,
      "type": "string",
      "nullable": true,
      "example": "Entity Title",
      "description": "Generated title for the entity based on schema title_template"
    },
    "_tags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "family:label"
      ],
      "description": "Entity Labels"
    },
    "calendar": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Calendar"
    },
    "subject": {
      "type": "string",
      "description": "Subject"
    },
    "description": {
      "type": "string",
      "description": "Description"
    },
    "event_type": {
      "type": "string",
      "enum": [
        "singleInstance",
        "occurrence",
        "exception",
        "seriesMaster"
      ],
      "description": "Event Type"
    },
    "status": {
      "type": "string",
      "enum": [
        "free",
        "tentative",
        "busy",
        "oof",
        "workingElsewhere",
        "unknown"
      ],
      "description": "Status"
    },
    "start_time": {
      "type": "string",
      "format": "date-time",
      "description": "Start Time"
    },
    "end_time": {
      "type": "string",
      "format": "date-time",
      "description": "End Time"
    },
    "timezone": {
      "type": "string",
      "description": "Timezone"
    },
    "is_all_day": {
      "type": "boolean",
      "description": "All Day"
    },
    "location": {
      "type": "string",
      "description": "Location"
    },
    "is_cancelled": {
      "type": "boolean",
      "description": "Cancelled"
    },
    "sensitivity": {
      "type": "string",
      "enum": [
        "normal",
        "personal",
        "private",
        "confidential"
      ],
      "description": "Sensitivity"
    },
    "importance": {
      "type": "string",
      "enum": [
        "low",
        "normal",
        "high"
      ],
      "description": "Importance"
    },
    "is_online_meeting": {
      "type": "boolean",
      "description": "Online Meeting"
    },
    "online_meeting_url": {
      "type": "string",
      "description": "Online Meeting URL"
    },
    "web_link": {
      "type": "string",
      "description": "Web Link"
    },
    "response_status": {
      "type": "string",
      "enum": [
        "none",
        "organizer",
        "tentativelyAccepted",
        "accepted",
        "declined",
        "notResponded"
      ],
      "description": "Response Status"
    },
    "organizer_email": {
      "type": "string",
      "format": "email",
      "description": "Organizer Email"
    },
    "attendees": {
      "type": "string",
      "description": "Attendees"
    },
    "is_recurring": {
      "type": "boolean",
      "description": "Recurring"
    },
    "series_master_id": {
      "type": "string",
      "description": "Series Master ID"
    },
    "source_type": {
      "type": "string",
      "enum": [
        "native",
        "synced"
      ],
      "description": "Source Type"
    },
    "source_provider": {
      "type": "string",
      "enum": [
        "outlook",
        "google"
      ],
      "description": "Source Provider"
    },
    "provider_event_id": {
      "type": "string",
      "description": "Provider Event ID"
    },
    "provider_event_url": {
      "type": "string",
      "description": "Provider Event URL"
    },
    "etag": {
      "type": "string",
      "description": "ETag"
    },
    "last_synced_at": {
      "type": "string",
      "format": "date-time",
      "description": "Last Synced At"
    },
    "_files": {
      "$ref": "#/definitions/BaseRelation"
    },
    "_created_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity creation"
    },
    "_updated_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity last update"
    },
    "_owners": {
      "type": "array",
      "readOnly": true,
      "items": {
        "description": "The user / organization owning this entity.\n\nNote: Owner implicitly has access to the entity regardless of ACLs.\n",
        "type": "object",
        "properties": {
          "org_id": {
            "type": "string",
            "example": "123"
          },
          "user_id": {
            "type": "string",
            "example": "456"
          }
        },
        "required": [
          "org_id"
        ]
      }
    },
    "_acl": {
      "readOnly": true,
      "type": "object",
      "description": "Access control list (ACL) for an entity. Defines sharing access to external orgs or users.",
      "additionalProperties": true,
      "properties": {
        "view": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "edit": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "delete": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        }
      }
    },
    "_manifest": {
      "readOnly": true,
      "type": "array",
      "nullable": true,
      "description": "Blueprint ID used to create/update the entity",
      "items": {
        "type": "string"
      },
      "example": [
        "123e4567-e89b-12d3-a456-426614174000"
      ]
    }
  },
  "definitions": {
    "BaseUUID": {
      "type": "string",
      "format": "uuid",
      "example": "123e4567-e89b-12d3-a456-426614174000"
    },
    "BaseTags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "example"
      ]
    },
    "BaseRelation": {
      "type": "object",
      "nullable": true,
      "description": "Relation to another entity",
      "properties": {
        "$relation": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "entity_id": {
                "$ref": "#/definitions/BaseUUID"
              },
              "_tags": {
                "$ref": "#/definitions/BaseTags"
              }
            }
          }
        }
      }
    }
  }
}

=== epilot-dev/docs/static/schemas/calendar_event-example.json
{
  "_schema": "calendar_event",
  "_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "_org": "123",
  "_title": "Entity Title",
  "_tags": [
    "family:label"
  ],
  "calendar": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "subject": "string",
  "description": "string",
  "event_type": "singleInstance",
  "status": "free",
  "start_time": "1970-01-01T00:00:00.000Z",
  "end_time": "1970-01-01T00:00:00.000Z",
  "timezone": "string",
  "is_all_day": true,
  "location": "string",
  "is_cancelled": true,
  "sensitivity": "normal",
  "importance": "low",
  "is_online_meeting": true,
  "online_meeting_url": "string",
  "web_link": "string",
  "response_status": "none",
  "organizer_email": "user@example.com",
  "attendees": "string",
  "is_recurring": true,
  "series_master_id": "string",
  "source_type": "native",
  "source_provider": "outlook",
  "provider_event_id": "string",
  "provider_event_url": "string",
  "etag": "string",
  "last_synced_at": "1970-01-01T00:00:00.000Z",
  "_files": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "_created_at": "1970-01-01T00:00:00.000Z",
  "_updated_at": "1970-01-01T00:00:00.000Z",
  "_owners": [
    {
      "org_id": "123",
      "user_id": "456"
    }
  ],
  "_acl": {
    "view": [
      "org:456"
    ],
    "edit": [
      "org:456"
    ],
    "delete": [
      "org:456"
    ]
  },
  "_manifest": [
    "123e4567-e89b-12d3-a456-426614174000"
  ]
}
