=== epilot-dev/docs/static/schemas/call-jsonschema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_schema"
  ],
  "properties": {
    "_schema": {
      "readOnly": true,
      "type": "string",
      "pattern": "^[a-zA-Z0-9_-]+$",
      "example": "call",
      "description": "URL-friendly identifier for the entity schema"
    },
    "_id": {
      "readOnly": true,
      "type": "string",
      "format": "uuid",
      "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "description": "Unique identifier for the entity"
    },
    "_org": {
      "type": "string",
      "description": "Organization Id the entity belongs to",
      "readOnly": true,
      "example": "123"
    },
    "_title": {
      "readOnly": true,
      "type": "string",
      "nullable": true,
      "example": "Entity Title",
      "description": "Generated title for the entity based on schema title_template"
    },
    "_tags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "family:label"
      ],
      "description": "Entity Labels"
    },
    "_purpose": {
      "$ref": "#/definitions/PurposeAttribute",
      "description": "Purposes"
    },
    "agent": {
      "$ref": "#/definitions/User",
      "description": "Agent"
    },
    "contact": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Contact"
    },
    "duration": {
      "type": "string",
      "description": "Duration (seconds)"
    },
    "recording": {
      "$ref": "#/definitions/LinkAttribute",
      "description": "Recording"
    },
    "transcript": {
      "type": "string",
      "description": "Transcript"
    },
    "external_id": {
      "type": "string",
      "description": "External ID"
    },
    "workflows": {
      "$ref": "#/definitions/WorkflowOverview"
    },
    "_files": {
      "$ref": "#/definitions/BaseRelation"
    },
    "_created_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity creation"
    },
    "_updated_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity last update"
    },
    "_owners": {
      "type": "array",
      "readOnly": true,
      "items": {
        "description": "The user / organization owning this entity.\n\nNote: Owner implicitly has access to the entity regardless of ACLs.\n",
        "type": "object",
        "properties": {
          "org_id": {
            "type": "string",
            "example": "123"
          },
          "user_id": {
            "type": "string",
            "example": "456"
          }
        },
        "required": [
          "org_id"
        ]
      }
    },
    "_acl": {
      "readOnly": true,
      "type": "object",
      "description": "Access control list (ACL) for an entity. Defines sharing access to external orgs or users.",
      "additionalProperties": true,
      "properties": {
        "view": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "edit": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "delete": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        }
      }
    },
    "_manifest": {
      "readOnly": true,
      "type": "array",
      "nullable": true,
      "description": "Blueprint ID used to create/update the entity",
      "items": {
        "type": "string"
      },
      "example": [
        "123e4567-e89b-12d3-a456-426614174000"
      ]
    }
  },
  "definitions": {
    "PurposeAttribute": {
      "type": "array",
      "description": "List of purpose ids",
      "items": {
        "type": "string"
      },
      "example": [
        "7675dc56-fd1b-46ee-9c35-defe0667b32e"
      ]
    },
    "LinkAttribute": {
      "type": "object",
      "description": "Link with title and href",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "link"
          ]
        },
        "title": {
          "type": "string",
          "example": "Visit Website"
        },
        "href": {
          "type": "string",
          "format": "uri",
          "example": "https://example.com"
        }
      }
    },
    "BaseUUID": {
      "type": "string",
      "format": "uuid",
      "example": "123e4567-e89b-12d3-a456-426614174000"
    },
    "BaseTags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "example"
      ]
    },
    "BaseRelation": {
      "type": "object",
      "nullable": true,
      "description": "Relation to another entity",
      "properties": {
        "$relation": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "entity_id": {
                "$ref": "#/definitions/BaseUUID"
              },
              "_tags": {
                "$ref": "#/definitions/BaseTags"
              }
            }
          }
        }
      }
    },
    "UserId": {
      "description": "User's unique identifier",
      "type": "string",
      "readOnly": true
    },
    "OrganizationId": {
      "description": "Organization unique identifier",
      "type": "string",
      "readOnly": true,
      "example": "123"
    },
    "User": {
      "type": "object",
      "description": "User information",
      "properties": {
        "id": {
          "$ref": "#/definitions/UserId"
        },
        "organization_id": {
          "$ref": "#/definitions/OrganizationId"
        },
        "email": {
          "type": "string",
          "format": "email",
          "example": "user@example.com"
        },
        "display_name": {
          "type": "string",
          "example": "John Doe",
          "deprecated": true
        },
        "name": {
          "type": "string",
          "example": "John Doe",
          "deprecated": true
        },
        "preferred_language": {
          "type": "string",
          "example": "de",
          "description": "ISO 639-1 language code"
        },
        "signature": {
          "type": "string",
          "example": "<p>Best regards,<br/>John Doe</p>",
          "description": "HTML email signature"
        },
        "roles": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "Owner"
          },
          "deprecated": true,
          "description": "Deprecated! Please use Permissions API instead"
        },
        "image_uri": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "original": {
              "type": "string",
              "format": "uri",
              "example": "https://account-profile-images.epilot.cloud/1/avatar.png"
            },
            "thumbnail_32": {
              "type": "string",
              "format": "uri",
              "example": "https://account-profile-images.epilot.cloud/1/avatar_32x32.png"
            }
          },
          "nullable": true
        },
        "properties": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "example": "profileImageName"
              },
              "value": {
                "type": "string",
                "example": "avatar.png"
              }
            },
            "required": [
              "name",
              "value"
            ]
          }
        }
      },
      "required": [
        "id",
        "organization_id",
        "email",
        "name",
        "preferred_language",
        "roles",
        "properties"
      ]
    },
    "WorkflowStatus": {
      "type": "string",
      "enum": [
        "STARTED",
        "DONE",
        "CLOSED"
      ]
    },
    "StepType": {
      "type": "string",
      "enum": [
        "MANUAL",
        "AUTOMATION"
      ]
    },
    "StepStatus": {
      "type": "string",
      "enum": [
        "UNASSIGNED",
        "ASSIGNED",
        "COMPLETED",
        "SKIPPED",
        "IN_PROGRESS"
      ]
    },
    "PhaseInEntity": {
      "type": "object",
      "description": "Workflow phase information",
      "properties": {
        "phase_id": {
          "type": "string"
        },
        "phase_name": {
          "type": "string"
        },
        "phase_progress": {
          "type": "number"
        }
      },
      "required": [
        "phase_id",
        "phase_name",
        "phase_progress"
      ]
    },
    "WorkflowInEntity": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "definition_id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/WorkflowStatus"
        },
        "assignees": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "progress": {
          "type": "number"
        },
        "phases_in_progress": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PhaseInEntity"
          }
        },
        "last_update_time": {
          "type": "string",
          "format": "date-time"
        },
        "upcoming_tasks_assignees": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "task_id": {
          "type": "string"
        },
        "task_name": {
          "type": "string"
        },
        "task_assignees": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "task_duedate": {
          "type": "string",
          "format": "date-time"
        },
        "task_execution_type": {
          "$ref": "#/definitions/StepType"
        },
        "task_status": {
          "$ref": "#/definitions/StepStatus"
        },
        "phase_id": {
          "type": "string"
        },
        "phase_name": {
          "type": "string"
        },
        "phase_assignees": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "phase_progress": {
          "type": "number"
        }
      },
      "required": [
        "id",
        "definition_id",
        "name",
        "status",
        "assignees",
        "last_update_time"
      ]
    },
    "WorkflowOverview": {
      "type": "object",
      "properties": {
        "primary": {
          "$ref": "#/definitions/WorkflowInEntity"
        }
      },
      "additionalProperties": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/WorkflowInEntity"
        }
      }
    }
  }
}

=== epilot-dev/docs/static/schemas/call-example.json
{
  "_schema": "call",
  "_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "_org": "123",
  "_title": "Entity Title",
  "_tags": [
    "family:label"
  ],
  "_purpose": [
    "7675dc56-fd1b-46ee-9c35-defe0667b32e"
  ],
  "agent": {
    "id": "string",
    "organization_id": "123",
    "email": "user@example.com",
    "display_name": "John Doe",
    "name": "John Doe",
    "preferred_language": "de",
    "signature": "<p>Best regards,<br/>John Doe</p>",
    "roles": [
      "Owner"
    ],
    "image_uri": {
      "original": "https://account-profile-images.epilot.cloud/1/avatar.png",
      "thumbnail_32": "https://account-profile-images.epilot.cloud/1/avatar_32x32.png"
    },
    "properties": [
      {
        "name": "profileImageName",
        "value": "avatar.png"
      }
    ]
  },
  "contact": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "duration": "string",
  "recording": {
    "type": "link",
    "title": "Visit Website",
    "href": "https://example.com"
  },
  "transcript": "string",
  "external_id": "string",
  "workflows": {
    "primary": {
      "id": "string",
      "definition_id": "string",
      "name": "string",
      "status": "STARTED",
      "assignees": [
        "string"
      ],
      "progress": 0,
      "phases_in_progress": [
        {
          "phase_id": "string",
          "phase_name": "string",
          "phase_progress": 0
        }
      ],
      "last_update_time": "1970-01-01T00:00:00.000Z",
      "upcoming_tasks_assignees": [
        "string"
      ],
      "task_id": "string",
      "task_name": "string",
      "task_assignees": [
        "string"
      ],
      "task_duedate": "1970-01-01T00:00:00.000Z",
      "task_execution_type": "MANUAL",
      "task_status": "UNASSIGNED",
      "phase_id": "string",
      "phase_name": "string",
      "phase_assignees": [
        "string"
      ],
      "phase_progress": 0
    }
  },
  "_files": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "_created_at": "1970-01-01T00:00:00.000Z",
  "_updated_at": "1970-01-01T00:00:00.000Z",
  "_owners": [
    {
      "org_id": "123",
      "user_id": "456"
    }
  ],
  "_acl": {
    "view": [
      "org:456"
    ],
    "edit": [
      "org:456"
    ],
    "delete": [
      "org:456"
    ]
  },
  "_manifest": [
    "123e4567-e89b-12d3-a456-426614174000"
  ]
}
