=== epilot-dev/docs/static/schemas/contact-jsonschema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_schema"
  ],
  "properties": {
    "_schema": {
      "readOnly": true,
      "type": "string",
      "pattern": "^[a-zA-Z0-9_-]+$",
      "example": "contact",
      "description": "URL-friendly identifier for the entity schema"
    },
    "_id": {
      "readOnly": true,
      "type": "string",
      "format": "uuid",
      "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "description": "Unique identifier for the entity"
    },
    "_org": {
      "type": "string",
      "description": "Organization Id the entity belongs to",
      "readOnly": true,
      "example": "123"
    },
    "_title": {
      "readOnly": true,
      "type": "string",
      "nullable": true,
      "example": "John Doe",
      "description": "Generated title for the entity based on schema title_template"
    },
    "_tags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "family:label"
      ],
      "description": "Entity Labels"
    },
    "_purpose": {
      "$ref": "#/definitions/PurposeAttribute",
      "description": "Purposes"
    },
    "salutation": {
      "type": "string",
      "enum": [
        "null",
        "Mr.",
        "Ms. / Mrs.",
        "Company",
        "Contact Person",
        "Company/Contact Person",
        "Spouse",
        "Family",
        "Ownership",
        "Assembly",
        "Other"
      ],
      "description": "Salutation"
    },
    "title": {
      "type": "string",
      "enum": [
        "null",
        "Dr.",
        "Prof.",
        "Prof. Dr."
      ],
      "description": "Title"
    },
    "first_name": {
      "type": "string",
      "description": "First Name"
    },
    "last_name": {
      "type": "string",
      "description": "Last Name"
    },
    "customer_number": {
      "type": "string",
      "description": "Customer Number"
    },
    "birthdate": {
      "type": "string",
      "format": "date",
      "example": "2025-01-01",
      "description": "Date of Birth"
    },
    "email": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "_tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "email": {
            "type": "string",
            "format": "email"
          }
        },
        "required": [
          "email"
        ]
      },
      "description": "Email"
    },
    "phone": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "_tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "phone": {
            "type": "string",
            "example": "+491234567890"
          }
        },
        "required": [
          "phone"
        ]
      },
      "description": "Phone"
    },
    "communication_preference": {
      "type": "string",
      "enum": [
        "postal",
        "portal"
      ],
      "description": "Standard communication method"
    },
    "address": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "Address attribute",
        "additionalProperties": true,
        "properties": {
          "_tags": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "example": [
              "billing"
            ]
          },
          "street": {
            "type": "string",
            "description": "The first line of the address. Typically the street address or PO Box number.",
            "nullable": true,
            "example": "Hauptstra√üe"
          },
          "street_number": {
            "type": "string",
            "description": "The second line of the address. Typically the number of the apartment, suite, or unit.",
            "nullable": true,
            "example": "123"
          },
          "postal_code": {
            "type": "string",
            "description": "The postal code for the address.",
            "nullable": true,
            "example": "50668"
          },
          "city": {
            "type": "string",
            "description": "The name of the city, district, village, or town.",
            "nullable": true,
            "example": "Cologne"
          },
          "country": {
            "type": "string",
            "description": "The two-letter code for the country of the address.",
            "nullable": true,
            "example": "DE"
          },
          "additional_info": {
            "type": "string",
            "description": "An additional description for the address",
            "nullable": true
          },
          "company_name": {
            "type": "string",
            "description": "the company name, usually used as extra delivery instructions",
            "nullable": true
          },
          "first_name": {
            "type": "string",
            "description": "the first name of the recipient, usually used as extra delivery instructions",
            "nullable": true
          },
          "last_name": {
            "type": "string",
            "description": "the last name of the recipient, usually used as extra delivery instructions",
            "nullable": true
          },
          "salutation": {
            "type": "string",
            "description": "the salutation of the recipient, usually used as extra delivery instructions",
            "nullable": true
          },
          "title": {
            "type": "string",
            "description": "the title of the recipient, usually used as extra delivery instructions",
            "nullable": true
          },
          "coordinates": {
            "type": "string",
            "description": "Geographical coordinates (latitude, longitude)",
            "nullable": true,
            "example": "50.948484, 6.943147"
          },
          "plot_of_land": {
            "type": "string",
            "description": "Plot of land information",
            "nullable": true
          },
          "plot_area": {
            "type": "string",
            "description": "Area of the plot",
            "nullable": true
          },
          "start_date": {
            "type": "string",
            "description": "Start date for the address",
            "format": "date",
            "nullable": true
          },
          "end_date": {
            "type": "string",
            "description": "End date for the address",
            "format": "date",
            "nullable": true
          }
        }
      },
      "description": "Address"
    },
    "payment": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "Payment method details",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "payment_sepa",
              "payment_invoice",
              "payment_cash"
            ],
            "example": "payment_sepa"
          },
          "data": {
            "type": "object",
            "properties": {
              "bank_name": {
                "type": "string",
                "example": "Deutsche Bank"
              },
              "iban": {
                "type": "string",
                "example": "DE89370400440532013000"
              },
              "bic_number": {
                "type": "string",
                "example": "DEUTDEFF"
              },
              "fullname": {
                "type": "string",
                "example": "John Doe"
              }
            }
          }
        }
      },
      "description": "Payment"
    },
    "account": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Account"
    },
    "marketing_permission": {
      "type": "boolean",
      "description": "Marketing Permission"
    },
    "contact_owner": {
      "$ref": "#/definitions/User",
      "description": "Contact Owner"
    },
    "represents_contact": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Represents Contact"
    },
    "consent_email_marketing": {
      "$ref": "#/definitions/ConsentAttribute",
      "description": "Email Marketing"
    },
    "consent_sms_marketing": {
      "$ref": "#/definitions/ConsentAttribute",
      "description": "SMS Marketing"
    },
    "consent_phone_call": {
      "$ref": "#/definitions/ConsentAttribute",
      "description": "Direct Phone Marketing"
    },
    "consent_print_marketing": {
      "$ref": "#/definitions/ConsentAttribute",
      "description": "Print Marketing"
    },
    "portal_users": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Portal Users"
    },
    "opportunities": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Opportunities"
    },
    "orders": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Orders"
    },
    "contracts": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Contracts"
    },
    "workflows": {
      "$ref": "#/definitions/WorkflowOverview"
    },
    "_files": {
      "$ref": "#/definitions/BaseRelation"
    },
    "_created_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity creation"
    },
    "_updated_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity last update"
    },
    "_owners": {
      "type": "array",
      "readOnly": true,
      "items": {
        "description": "The user / organization owning this entity.\n\nNote: Owner implicitly has access to the entity regardless of ACLs.\n",
        "type": "object",
        "properties": {
          "org_id": {
            "type": "string",
            "example": "123"
          },
          "user_id": {
            "type": "string",
            "example": "456"
          }
        },
        "required": [
          "org_id"
        ]
      }
    },
    "_acl": {
      "readOnly": true,
      "type": "object",
      "description": "Access control list (ACL) for an entity. Defines sharing access to external orgs or users.",
      "additionalProperties": true,
      "properties": {
        "view": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "edit": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "delete": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        }
      }
    },
    "_manifest": {
      "readOnly": true,
      "type": "array",
      "nullable": true,
      "description": "Blueprint ID used to create/update the entity",
      "items": {
        "type": "string"
      },
      "example": [
        "123e4567-e89b-12d3-a456-426614174000"
      ]
    }
  },
  "definitions": {
    "PurposeAttribute": {
      "type": "array",
      "description": "List of purpose ids",
      "items": {
        "type": "string"
      },
      "example": [
        "7675dc56-fd1b-46ee-9c35-defe0667b32e"
      ]
    },
    "ConsentAttribute": {
      "type": "object",
      "description": "Consent Management",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "consent"
          ]
        },
        "topic": {
          "type": "string"
        },
        "identifiers": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "type",
        "topic"
      ]
    },
    "BaseUUID": {
      "type": "string",
      "format": "uuid",
      "example": "123e4567-e89b-12d3-a456-426614174000"
    },
    "BaseTags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "example"
      ]
    },
    "BaseRelation": {
      "type": "object",
      "nullable": true,
      "description": "Relation to another entity",
      "properties": {
        "$relation": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "entity_id": {
                "$ref": "#/definitions/BaseUUID"
              },
              "_tags": {
                "$ref": "#/definitions/BaseTags"
              }
            }
          }
        }
      }
    },
    "UserId": {
      "description": "User's unique identifier",
      "type": "string",
      "readOnly": true
    },
    "OrganizationId": {
      "description": "Organization unique identifier",
      "type": "string",
      "readOnly": true,
      "example": "123"
    },
    "User": {
      "type": "object",
      "description": "User information",
      "properties": {
        "id": {
          "$ref": "#/definitions/UserId"
        },
        "organization_id": {
          "$ref": "#/definitions/OrganizationId"
        },
        "email": {
          "type": "string",
          "format": "email",
          "example": "user@example.com"
        },
        "display_name": {
          "type": "string",
          "example": "John Doe",
          "deprecated": true
        },
        "name": {
          "type": "string",
          "example": "John Doe",
          "deprecated": true
        },
        "preferred_language": {
          "type": "string",
          "example": "de",
          "description": "ISO 639-1 language code"
        },
        "signature": {
          "type": "string",
          "example": "<p>Best regards,<br/>John Doe</p>",
          "description": "HTML email signature"
        },
        "roles": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "Owner"
          },
          "deprecated": true,
          "description": "Deprecated! Please use Permissions API instead"
        },
        "image_uri": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "original": {
              "type": "string",
              "format": "uri",
              "example": "https://account-profile-images.epilot.cloud/1/avatar.png"
            },
            "thumbnail_32": {
              "type": "string",
              "format": "uri",
              "example": "https://account-profile-images.epilot.cloud/1/avatar_32x32.png"
            }
          },
          "nullable": true
        },
        "properties": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "example": "profileImageName"
              },
              "value": {
                "type": "string",
                "example": "avatar.png"
              }
            },
            "required": [
              "name",
              "value"
            ]
          }
        }
      },
      "required": [
        "id",
        "organization_id",
        "email",
        "name",
        "preferred_language",
        "roles",
        "properties"
      ]
    },
    "WorkflowStatus": {
      "type": "string",
      "enum": [
        "STARTED",
        "DONE",
        "CLOSED"
      ]
    },
    "StepType": {
      "type": "string",
      "enum": [
        "MANUAL",
        "AUTOMATION"
      ]
    },
    "StepStatus": {
      "type": "string",
      "enum": [
        "UNASSIGNED",
        "ASSIGNED",
        "COMPLETED",
        "SKIPPED",
        "IN_PROGRESS"
      ]
    },
    "PhaseInEntity": {
      "type": "object",
      "description": "Workflow phase information",
      "properties": {
        "phase_id": {
          "type": "string"
        },
        "phase_name": {
          "type": "string"
        },
        "phase_progress": {
          "type": "number"
        }
      },
      "required": [
        "phase_id",
        "phase_name",
        "phase_progress"
      ]
    },
    "WorkflowInEntity": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "definition_id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/WorkflowStatus"
        },
        "assignees": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "progress": {
          "type": "number"
        },
        "phases_in_progress": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PhaseInEntity"
          }
        },
        "last_update_time": {
          "type": "string",
          "format": "date-time"
        },
        "upcoming_tasks_assignees": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "task_id": {
          "type": "string"
        },
        "task_name": {
          "type": "string"
        },
        "task_assignees": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "task_duedate": {
          "type": "string",
          "format": "date-time"
        },
        "task_execution_type": {
          "$ref": "#/definitions/StepType"
        },
        "task_status": {
          "$ref": "#/definitions/StepStatus"
        },
        "phase_id": {
          "type": "string"
        },
        "phase_name": {
          "type": "string"
        },
        "phase_assignees": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "phase_progress": {
          "type": "number"
        }
      },
      "required": [
        "id",
        "definition_id",
        "name",
        "status",
        "assignees",
        "phases_in_progress",
        "last_update_time"
      ]
    },
    "WorkflowOverview": {
      "type": "object",
      "properties": {
        "primary": {
          "$ref": "#/definitions/WorkflowInEntity"
        }
      },
      "additionalProperties": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/WorkflowInEntity"
        }
      }
    }
  }
}

=== epilot-dev/docs/static/schemas/contact-example.json
{
  "_schema": "contact",
  "_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "_org": "123",
  "_title": "John Doe",
  "_tags": [
    "family:label"
  ],
  "_purpose": [
    "7675dc56-fd1b-46ee-9c35-defe0667b32e"
  ],
  "salutation": "null",
  "title": "null",
  "first_name": "string",
  "last_name": "string",
  "customer_number": "string",
  "birthdate": "2025-01-01",
  "email": [
    {
      "_tags": [
        "string"
      ],
      "email": "user@example.com"
    }
  ],
  "phone": [
    {
      "_tags": [
        "string"
      ],
      "phone": "+491234567890"
    }
  ],
  "communication_preference": "postal",
  "address": [
    {
      "_tags": [
        "billing"
      ],
      "street": "Hauptstra√üe",
      "street_number": "123",
      "postal_code": "50668",
      "city": "Cologne",
      "country": "DE",
      "additional_info": "string",
      "company_name": "string",
      "first_name": "string",
      "last_name": "string",
      "salutation": "string",
      "title": "string",
      "coordinates": "50.948484, 6.943147",
      "plot_of_land": "string",
      "plot_area": "string",
      "start_date": "1970-01-01",
      "end_date": "1970-01-01"
    }
  ],
  "payment": [
    {
      "type": "payment_sepa",
      "data": {
        "bank_name": "Deutsche Bank",
        "iban": "DE89370400440532013000",
        "bic_number": "DEUTDEFF",
        "fullname": "John Doe"
      }
    }
  ],
  "account": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "marketing_permission": true,
  "contact_owner": {
    "id": "string",
    "organization_id": "123",
    "email": "user@example.com",
    "display_name": "John Doe",
    "name": "John Doe",
    "preferred_language": "de",
    "signature": "<p>Best regards,<br/>John Doe</p>",
    "roles": [
      "Owner"
    ],
    "image_uri": {
      "original": "https://account-profile-images.epilot.cloud/1/avatar.png",
      "thumbnail_32": "https://account-profile-images.epilot.cloud/1/avatar_32x32.png"
    },
    "properties": [
      {
        "name": "profileImageName",
        "value": "avatar.png"
      }
    ]
  },
  "represents_contact": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "consent_email_marketing": {
    "type": "consent",
    "topic": "string",
    "identifiers": [
      "string"
    ]
  },
  "consent_sms_marketing": {
    "type": "consent",
    "topic": "string",
    "identifiers": [
      "string"
    ]
  },
  "consent_phone_call": {
    "type": "consent",
    "topic": "string",
    "identifiers": [
      "string"
    ]
  },
  "consent_print_marketing": {
    "type": "consent",
    "topic": "string",
    "identifiers": [
      "string"
    ]
  },
  "portal_users": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "opportunities": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "orders": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "contracts": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "workflows": {
    "primary": {
      "id": "string",
      "definition_id": "string",
      "name": "string",
      "status": "STARTED",
      "assignees": [
        "string"
      ],
      "progress": 0,
      "phases_in_progress": [
        {
          "phase_id": "string",
          "phase_name": "string",
          "phase_progress": 0
        }
      ],
      "last_update_time": "1970-01-01T00:00:00.000Z",
      "upcoming_tasks_assignees": [
        "string"
      ],
      "task_id": "string",
      "task_name": "string",
      "task_assignees": [
        "string"
      ],
      "task_duedate": "1970-01-01T00:00:00.000Z",
      "task_execution_type": "MANUAL",
      "task_status": "UNASSIGNED",
      "phase_id": "string",
      "phase_name": "string",
      "phase_assignees": [
        "string"
      ],
      "phase_progress": 0
    }
  },
  "_files": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "_created_at": "1970-01-01T00:00:00.000Z",
  "_updated_at": "1970-01-01T00:00:00.000Z",
  "_owners": [
    {
      "org_id": "123",
      "user_id": "456"
    }
  ],
  "_acl": {
    "view": [
      "org:456"
    ],
    "edit": [
      "org:456"
    ],
    "delete": [
      "org:456"
    ]
  },
  "_manifest": [
    "123e4567-e89b-12d3-a456-426614174000"
  ]
}
