=== epilot-dev/docs/static/schemas/coupon-jsonschema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_schema",
    "name",
    "percentage_value",
    "fixed_value"
  ],
  "properties": {
    "_schema": {
      "readOnly": true,
      "type": "string",
      "pattern": "^[a-zA-Z0-9_-]+$",
      "example": "coupon",
      "description": "URL-friendly identifier for the entity schema"
    },
    "_id": {
      "readOnly": true,
      "type": "string",
      "format": "uuid",
      "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "description": "Unique identifier for the entity"
    },
    "_org": {
      "type": "string",
      "description": "Organization Id the entity belongs to",
      "readOnly": true,
      "example": "123"
    },
    "_title": {
      "readOnly": true,
      "type": "string",
      "nullable": true,
      "example": "Entity Title",
      "description": "Generated title for the entity based on schema title_template"
    },
    "_tags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "family:label"
      ],
      "description": "Entity Labels"
    },
    "_purpose": {
      "$ref": "#/definitions/PurposeAttribute",
      "description": "Purposes"
    },
    "name": {
      "type": "string",
      "description": "Name"
    },
    "description": {
      "type": "string",
      "description": "Description"
    },
    "type": {
      "type": "string",
      "enum": [
        "percentage",
        "fixed"
      ],
      "description": "Type"
    },
    "percentage_value": {
      "type": "string",
      "description": "Value (%)"
    },
    "fixed_value_currency": {
      "type": "string",
      "description": "Three-letter ISO currency code, in lowercase. Must be a supported currency.",
      "example": "EUR"
    },
    "fixed_value_decimal": {
      "type": "string",
      "description": "The currency value as a decimal string",
      "example": "123.45"
    },
    "fixed_value": {
      "type": "number",
      "description": "Value (€)"
    },
    "category": {
      "type": "string",
      "description": "What type of coupon is it?"
    },
    "cashback_period": {
      "type": "string",
      "description": "When should it be applied?"
    },
    "active": {
      "type": "boolean",
      "description": "Available"
    },
    "prices": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Promoted prices"
    },
    "_files": {
      "$ref": "#/definitions/BaseRelation"
    },
    "_created_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity creation"
    },
    "_updated_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity last update"
    },
    "_owners": {
      "type": "array",
      "readOnly": true,
      "items": {
        "description": "The user / organization owning this entity.\n\nNote: Owner implicitly has access to the entity regardless of ACLs.\n",
        "type": "object",
        "properties": {
          "org_id": {
            "type": "string",
            "example": "123"
          },
          "user_id": {
            "type": "string",
            "example": "456"
          }
        },
        "required": [
          "org_id"
        ]
      }
    },
    "_acl": {
      "readOnly": true,
      "type": "object",
      "description": "Access control list (ACL) for an entity. Defines sharing access to external orgs or users.",
      "additionalProperties": true,
      "properties": {
        "view": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "edit": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "delete": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        }
      }
    },
    "_manifest": {
      "readOnly": true,
      "type": "array",
      "nullable": true,
      "description": "Blueprint ID used to create/update the entity",
      "items": {
        "type": "string"
      },
      "example": [
        "123e4567-e89b-12d3-a456-426614174000"
      ]
    }
  },
  "definitions": {
    "PurposeAttribute": {
      "type": "array",
      "description": "List of purpose ids",
      "items": {
        "type": "string"
      },
      "example": [
        "7675dc56-fd1b-46ee-9c35-defe0667b32e"
      ]
    },
    "BaseUUID": {
      "type": "string",
      "format": "uuid",
      "example": "123e4567-e89b-12d3-a456-426614174000"
    },
    "BaseTags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "example"
      ]
    },
    "BaseRelation": {
      "type": "object",
      "nullable": true,
      "description": "Relation to another entity",
      "properties": {
        "$relation": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "entity_id": {
                "$ref": "#/definitions/BaseUUID"
              },
              "_tags": {
                "$ref": "#/definitions/BaseTags"
              }
            }
          }
        }
      }
    }
  }
}

=== epilot-dev/docs/static/schemas/coupon-example.json
{
  "_schema": "coupon",
  "_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "_org": "123",
  "_title": "Entity Title",
  "_tags": [
    "family:label"
  ],
  "_purpose": [
    "7675dc56-fd1b-46ee-9c35-defe0667b32e"
  ],
  "name": "string",
  "description": "string",
  "type": "percentage",
  "percentage_value": "string",
  "fixed_value_currency": "EUR",
  "fixed_value_decimal": "123.45",
  "fixed_value": 0,
  "category": "string",
  "cashback_period": "string",
  "active": true,
  "prices": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "_files": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "_created_at": "1970-01-01T00:00:00.000Z",
  "_updated_at": "1970-01-01T00:00:00.000Z",
  "_owners": [
    {
      "org_id": "123",
      "user_id": "456"
    }
  ],
  "_acl": {
    "view": [
      "org:456"
    ],
    "edit": [
      "org:456"
    ],
    "delete": [
      "org:456"
    ]
  },
  "_manifest": [
    "123e4567-e89b-12d3-a456-426614174000"
  ]
}
