=== epilot-dev/docs/static/schemas/file-jsonschema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_schema",
    "filename",
    "language"
  ],
  "properties": {
    "_schema": {
      "readOnly": true,
      "type": "string",
      "pattern": "^[a-zA-Z0-9_-]+$",
      "example": "file",
      "description": "URL-friendly identifier for the entity schema"
    },
    "_id": {
      "readOnly": true,
      "type": "string",
      "format": "uuid",
      "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "description": "Unique identifier for the entity"
    },
    "_org": {
      "type": "string",
      "description": "Organization Id the entity belongs to",
      "readOnly": true,
      "example": "123"
    },
    "_title": {
      "readOnly": true,
      "type": "string",
      "nullable": true,
      "example": "Entity Title",
      "description": "Generated title for the entity based on schema title_template"
    },
    "_tags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "family:label"
      ],
      "description": "Entity Labels"
    },
    "_purpose": {
      "$ref": "#/definitions/PurposeAttribute",
      "description": "Purposes"
    },
    "_thumbnail": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Thumbnail"
    },
    "filename": {
      "type": "string",
      "description": "File Name"
    },
    "mime_type": {
      "type": "string",
      "description": "MIME Type"
    },
    "type": {
      "type": "string",
      "enum": [
        "document",
        "document_template",
        "text",
        "image",
        "video",
        "audio",
        "spreadsheet",
        "presentation",
        "font",
        "archive",
        "application",
        "unknown"
      ],
      "description": "File Type"
    },
    "readable_size": {
      "type": "string",
      "description": "Size"
    },
    "language": {
      "type": "string",
      "enum": [
        "de",
        "en"
      ],
      "description": "Language"
    },
    "alt_text": {
      "type": "string",
      "description": "Alt text"
    },
    "access_control": {
      "type": "string",
      "enum": [
        "private",
        "public-read"
      ],
      "description": "Access Control"
    },
    "public_url": {
      "type": "string",
      "description": "Public URL"
    },
    "shared_with_end_customer": {
      "type": "boolean",
      "description": "Shared with End Customer"
    },
    "category": {
      "type": "string",
      "enum": [
        "address-suggestions",
        "unknown"
      ],
      "description": "Category"
    },
    "file_date": {
      "type": "string",
      "format": "date",
      "example": "2025-01-01",
      "description": "File Date"
    },
    "external_id": {
      "type": "string",
      "description": "External ID"
    },
    "custom_download_url": {
      "type": "string",
      "description": "Custom Download URL"
    },
    "custom_download_url_auth": {
      "type": "string",
      "description": "Custom Download URL Auth"
    },
    "journeys": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Journeys"
    },
    "preview_summary_de": {
      "type": "string",
      "description": "Preview Summary (DE)"
    },
    "short_summary_de": {
      "type": "string",
      "description": "Short Summary (DE)"
    },
    "preview_summary_en": {
      "type": "string",
      "description": "Preview Summary (EN)"
    },
    "short_summary_en": {
      "type": "string",
      "description": "Short Summary (EN)"
    },
    "summary_status": {
      "type": "string",
      "enum": [
        "processing",
        "completed",
        "failed",
        "unsupported"
      ],
      "description": "Summary Status"
    },
    "_files": {
      "$ref": "#/definitions/BaseRelation"
    },
    "_created_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity creation"
    },
    "_updated_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity last update"
    },
    "_owners": {
      "type": "array",
      "readOnly": true,
      "items": {
        "description": "The user / organization owning this entity.\n\nNote: Owner implicitly has access to the entity regardless of ACLs.\n",
        "type": "object",
        "properties": {
          "org_id": {
            "type": "string",
            "example": "123"
          },
          "user_id": {
            "type": "string",
            "example": "456"
          }
        },
        "required": [
          "org_id"
        ]
      }
    },
    "_acl": {
      "readOnly": true,
      "type": "object",
      "description": "Access control list (ACL) for an entity. Defines sharing access to external orgs or users.",
      "additionalProperties": true,
      "properties": {
        "view": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "edit": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "delete": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        }
      }
    },
    "_manifest": {
      "readOnly": true,
      "type": "array",
      "nullable": true,
      "description": "Blueprint ID used to create/update the entity",
      "items": {
        "type": "string"
      },
      "example": [
        "123e4567-e89b-12d3-a456-426614174000"
      ]
    }
  },
  "definitions": {
    "PurposeAttribute": {
      "type": "array",
      "description": "List of purpose ids",
      "items": {
        "type": "string"
      },
      "example": [
        "7675dc56-fd1b-46ee-9c35-defe0667b32e"
      ]
    },
    "BaseUUID": {
      "type": "string",
      "format": "uuid",
      "example": "123e4567-e89b-12d3-a456-426614174000"
    },
    "BaseTags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "example"
      ]
    },
    "BaseRelation": {
      "type": "object",
      "nullable": true,
      "description": "Relation to another entity",
      "properties": {
        "$relation": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "entity_id": {
                "$ref": "#/definitions/BaseUUID"
              },
              "_tags": {
                "$ref": "#/definitions/BaseTags"
              }
            }
          }
        }
      }
    }
  }
}

=== epilot-dev/docs/static/schemas/file-example.json
{
  "_schema": "file",
  "_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "_org": "123",
  "_title": "Entity Title",
  "_tags": [
    "family:label"
  ],
  "_purpose": [
    "7675dc56-fd1b-46ee-9c35-defe0667b32e"
  ],
  "_thumbnail": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "filename": "string",
  "mime_type": "string",
  "type": "document",
  "readable_size": "string",
  "language": "de",
  "alt_text": "string",
  "access_control": "private",
  "public_url": "string",
  "shared_with_end_customer": true,
  "category": "address-suggestions",
  "file_date": "2025-01-01",
  "external_id": "string",
  "preview_summary_de": "string",
  "short_summary_de": "string",
  "preview_summary_en": "string",
  "short_summary_en": "string",
  "summary_status": "processing",
  "_files": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "_created_at": "1970-01-01T00:00:00.000Z",
  "_updated_at": "1970-01-01T00:00:00.000Z",
  "_owners": [
    {
      "org_id": "123",
      "user_id": "456"
    }
  ],
  "_acl": {
    "view": [
      "org:456"
    ],
    "edit": [
      "org:456"
    ],
    "delete": [
      "org:456"
    ]
  },
  "_manifest": [
    "123e4567-e89b-12d3-a456-426614174000"
  ]
}
