=== epilot-dev/docs/static/schemas/journey-jsonschema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_schema"
  ],
  "properties": {
    "_schema": {
      "readOnly": true,
      "type": "string",
      "pattern": "^[a-zA-Z0-9_-]+$",
      "example": "journey",
      "description": "URL-friendly identifier for the entity schema"
    },
    "_id": {
      "readOnly": true,
      "type": "string",
      "format": "uuid",
      "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "description": "Unique identifier for the entity"
    },
    "_org": {
      "type": "string",
      "description": "Organization Id the entity belongs to",
      "readOnly": true,
      "example": "123"
    },
    "_title": {
      "readOnly": true,
      "type": "string",
      "nullable": true,
      "example": "Entity Title",
      "description": "Generated title for the entity based on schema title_template"
    },
    "_tags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "family:label"
      ],
      "description": "Entity Labels"
    },
    "_purpose": {
      "$ref": "#/definitions/PurposeAttribute",
      "description": "Purposes"
    },
    "journey_name": {
      "type": "string",
      "description": "Journey name"
    },
    "journey_id": {
      "type": "string",
      "description": "Journey Id"
    },
    "journey_type": {
      "type": "string",
      "description": "Journey Type"
    },
    "access_mode": {
      "type": "string",
      "enum": [
        "PUBLIC",
        "PRIVATE"
      ],
      "description": "Journey Access Mode"
    },
    "design": {
      "type": "string",
      "description": "Design"
    },
    "created_by": {
      "$ref": "#/definitions/User",
      "description": "Created by"
    },
    "journey_version": {
      "type": "string",
      "description": "Version"
    },
    "is_active": {
      "type": "boolean",
      "description": "Published"
    },
    "products": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Products"
    },
    "prices": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Prices"
    },
    "files": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Files"
    },
    "_files": {
      "$ref": "#/definitions/BaseRelation"
    },
    "_created_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity creation"
    },
    "_updated_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity last update"
    },
    "_owners": {
      "type": "array",
      "readOnly": true,
      "items": {
        "description": "The user / organization owning this entity.\n\nNote: Owner implicitly has access to the entity regardless of ACLs.\n",
        "type": "object",
        "properties": {
          "org_id": {
            "type": "string",
            "example": "123"
          },
          "user_id": {
            "type": "string",
            "example": "456"
          }
        },
        "required": [
          "org_id"
        ]
      }
    },
    "_acl": {
      "readOnly": true,
      "type": "object",
      "description": "Access control list (ACL) for an entity. Defines sharing access to external orgs or users.",
      "additionalProperties": true,
      "properties": {
        "view": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "edit": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "delete": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        }
      }
    },
    "_manifest": {
      "readOnly": true,
      "type": "array",
      "nullable": true,
      "description": "Blueprint ID used to create/update the entity",
      "items": {
        "type": "string"
      },
      "example": [
        "123e4567-e89b-12d3-a456-426614174000"
      ]
    }
  },
  "definitions": {
    "PurposeAttribute": {
      "type": "array",
      "description": "List of purpose ids",
      "items": {
        "type": "string"
      },
      "example": [
        "7675dc56-fd1b-46ee-9c35-defe0667b32e"
      ]
    },
    "BaseUUID": {
      "type": "string",
      "format": "uuid",
      "example": "123e4567-e89b-12d3-a456-426614174000"
    },
    "BaseTags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "example"
      ]
    },
    "BaseRelation": {
      "type": "object",
      "nullable": true,
      "description": "Relation to another entity",
      "properties": {
        "$relation": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "entity_id": {
                "$ref": "#/definitions/BaseUUID"
              },
              "_tags": {
                "$ref": "#/definitions/BaseTags"
              }
            }
          }
        }
      }
    },
    "UserId": {
      "description": "User's unique identifier",
      "type": "string",
      "readOnly": true
    },
    "OrganizationId": {
      "description": "Organization unique identifier",
      "type": "string",
      "readOnly": true,
      "example": "123"
    },
    "User": {
      "type": "object",
      "description": "User information",
      "properties": {
        "id": {
          "$ref": "#/definitions/UserId"
        },
        "organization_id": {
          "$ref": "#/definitions/OrganizationId"
        },
        "email": {
          "type": "string",
          "format": "email",
          "example": "user@example.com"
        },
        "display_name": {
          "type": "string",
          "example": "John Doe",
          "deprecated": true
        },
        "name": {
          "type": "string",
          "example": "John Doe",
          "deprecated": true
        },
        "preferred_language": {
          "type": "string",
          "example": "de",
          "description": "ISO 639-1 language code"
        },
        "signature": {
          "type": "string",
          "example": "<p>Best regards,<br/>John Doe</p>",
          "description": "HTML email signature"
        },
        "roles": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "Owner"
          },
          "deprecated": true,
          "description": "Deprecated! Please use Permissions API instead"
        },
        "image_uri": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "original": {
              "type": "string",
              "format": "uri",
              "example": "https://account-profile-images.epilot.cloud/1/avatar.png"
            },
            "thumbnail_32": {
              "type": "string",
              "format": "uri",
              "example": "https://account-profile-images.epilot.cloud/1/avatar_32x32.png"
            }
          },
          "nullable": true
        },
        "properties": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "example": "profileImageName"
              },
              "value": {
                "type": "string",
                "example": "avatar.png"
              }
            },
            "required": [
              "name",
              "value"
            ]
          }
        }
      },
      "required": [
        "id",
        "organization_id",
        "email",
        "name",
        "preferred_language",
        "roles",
        "properties"
      ]
    }
  }
}

=== epilot-dev/docs/static/schemas/journey-example.json
{
  "_schema": "journey",
  "_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "_org": "123",
  "_title": "Entity Title",
  "_tags": [
    "family:label"
  ],
  "_purpose": [
    "7675dc56-fd1b-46ee-9c35-defe0667b32e"
  ],
  "journey_name": "string",
  "journey_id": "string",
  "journey_type": "string",
  "access_mode": "PUBLIC",
  "design": "string",
  "created_by": {
    "id": "string",
    "organization_id": "123",
    "email": "user@example.com",
    "display_name": "John Doe",
    "name": "John Doe",
    "preferred_language": "de",
    "signature": "<p>Best regards,<br/>John Doe</p>",
    "roles": [
      "Owner"
    ],
    "image_uri": {
      "original": "https://account-profile-images.epilot.cloud/1/avatar.png",
      "thumbnail_32": "https://account-profile-images.epilot.cloud/1/avatar_32x32.png"
    },
    "properties": [
      {
        "name": "profileImageName",
        "value": "avatar.png"
      }
    ]
  },
  "journey_version": "string",
  "is_active": true,
  "products": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "prices": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "files": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "_files": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "_created_at": "1970-01-01T00:00:00.000Z",
  "_updated_at": "1970-01-01T00:00:00.000Z",
  "_owners": [
    {
      "org_id": "123",
      "user_id": "456"
    }
  ],
  "_acl": {
    "view": [
      "org:456"
    ],
    "edit": [
      "org:456"
    ],
    "delete": [
      "org:456"
    ]
  },
  "_manifest": [
    "123e4567-e89b-12d3-a456-426614174000"
  ]
}
