=== epilot-dev/docs/static/schemas/message-jsonschema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_schema"
  ],
  "properties": {
    "_schema": {
      "readOnly": true,
      "type": "string",
      "pattern": "^[a-zA-Z0-9_-]+$",
      "example": "contact",
      "description": "URL-friendly identifier for the entity schema"
    },
    "_id": {
      "readOnly": true,
      "type": "string",
      "format": "uuid",
      "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "description": "Unique identifier for the entity"
    },
    "_org": {
      "type": "string",
      "description": "Organization Id the entity belongs to",
      "readOnly": true,
      "example": "123"
    },
    "_title": {
      "readOnly": true,
      "type": "string",
      "nullable": true,
      "example": "John Doe",
      "description": "Generated title for the entity based on schema title_template"
    },
    "_tags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "family:label"
      ],
      "description": "Entity Labels"
    },
    "received_at": {
      "type": "string",
      "format": "date-time",
      "description": "Received at"
    },
    "sent_at": {
      "type": "string",
      "format": "date-time",
      "description": "Sent at"
    },
    "type": {
      "type": "string",
      "description": "Type"
    },
    "text": {
      "type": "string",
      "description": "Content"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Tags"
    },
    "attachments": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Attachments"
    },
    "thread": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Parent Thread"
    },
    "opportunity": {
      "$ref": "#/definitions/BaseRelation",
      "description": "opportunity"
    },
    "order": {
      "$ref": "#/definitions/BaseRelation",
      "description": "order"
    },
    "contract": {
      "$ref": "#/definitions/BaseRelation",
      "description": "contract"
    },
    "contact": {
      "$ref": "#/definitions/BaseRelation",
      "description": "contact"
    },
    "account": {
      "$ref": "#/definitions/BaseRelation",
      "description": "account"
    },
    "meter": {
      "$ref": "#/definitions/BaseRelation",
      "description": "meter"
    },
    "partner": {
      "$ref": "#/definitions/BaseRelation",
      "description": "partner"
    },
    "request": {
      "$ref": "#/definitions/BaseRelation",
      "description": "request"
    },
    "_files": {
      "$ref": "#/definitions/BaseRelation"
    },
    "_created_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity creation"
    },
    "_updated_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity last update"
    },
    "_owners": {
      "type": "array",
      "readOnly": true,
      "items": {
        "description": "The user / organization owning this entity.\n\nNote: Owner implicitly has access to the entity regardless of ACLs.\n",
        "type": "object",
        "properties": {
          "org_id": {
            "type": "string",
            "example": "123"
          },
          "user_id": {
            "type": "string",
            "example": "456"
          }
        },
        "required": [
          "org_id"
        ]
      }
    },
    "_acl": {
      "readOnly": true,
      "type": "object",
      "description": "Access control list (ACL) for an entity. Defines sharing access to external orgs or users.",
      "additionalProperties": true,
      "properties": {
        "view": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "edit": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "delete": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        }
      }
    },
    "_manifest": {
      "readOnly": true,
      "type": "array",
      "nullable": true,
      "description": "Blueprint ID used to create/update the entity",
      "items": {
        "type": "string"
      },
      "example": [
        "123e4567-e89b-12d3-a456-426614174000"
      ]
    }
  },
  "definitions": {
    "BaseUUID": {
      "type": "string",
      "format": "uuid",
      "example": "123e4567-e89b-12d3-a456-426614174000"
    },
    "BaseTags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "example"
      ]
    },
    "BaseRelation": {
      "type": "object",
      "nullable": true,
      "description": "Relation to another entity",
      "properties": {
        "$relation": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "entity_id": {
                "$ref": "#/definitions/BaseUUID"
              },
              "_tags": {
                "$ref": "#/definitions/BaseTags"
              }
            }
          }
        }
      }
    }
  }
}

=== epilot-dev/docs/static/schemas/message-example.json
{
  "_schema": "message",
  "_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "_org": "123",
  "_title": "John Doe",
  "_tags": [
    "family:label"
  ],
  "received_at": "1970-01-01T00:00:00.000Z",
  "sent_at": "1970-01-01T00:00:00.000Z",
  "type": "string",
  "text": "string",
  "tags": [
    "string"
  ],
  "attachments": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "thread": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "opportunity": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "order": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "contract": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "contact": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "account": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "meter": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "partner": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "request": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "_files": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "_created_at": "1970-01-01T00:00:00.000Z",
  "_updated_at": "1970-01-01T00:00:00.000Z",
  "_owners": [
    {
      "org_id": "123",
      "user_id": "456"
    }
  ],
  "_acl": {
    "view": [
      "org:456"
    ],
    "edit": [
      "org:456"
    ],
    "delete": [
      "org:456"
    ]
  },
  "_manifest": [
    "123e4567-e89b-12d3-a456-426614174000"
  ]
}
