=== epilot-dev/docs/static/schemas/partner-jsonschema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_schema",
    "status",
    "company_name_title",
    "email"
  ],
  "properties": {
    "_schema": {
      "readOnly": true,
      "type": "string",
      "pattern": "^[a-zA-Z0-9_-]+$",
      "example": "contact",
      "description": "URL-friendly identifier for the entity schema"
    },
    "_id": {
      "readOnly": true,
      "type": "string",
      "format": "uuid",
      "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "description": "Unique identifier for the entity"
    },
    "_org": {
      "type": "string",
      "description": "Organization Id the entity belongs to",
      "readOnly": true,
      "example": "123"
    },
    "_title": {
      "readOnly": true,
      "type": "string",
      "nullable": true,
      "example": "John Doe",
      "description": "Generated title for the entity based on schema title_template"
    },
    "_tags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "family:label"
      ],
      "description": "Entity Labels"
    },
    "_purpose": {
      "$ref": "#/definitions/PurposeAttribute",
      "description": "Purposes"
    },
    "status": {
      "type": "string",
      "description": "Status"
    },
    "company_name_title": {
      "type": "string",
      "description": "Partner Name"
    },
    "description": {
      "type": "string",
      "description": "Description"
    },
    "address": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "Address attribute",
        "additionalProperties": true,
        "properties": {
          "_tags": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "example": [
              "billing"
            ]
          },
          "street": {
            "type": "string",
            "description": "The first line of the address. Typically the street address or PO Box number.",
            "nullable": true,
            "example": "Hauptstra√üe"
          },
          "street_number": {
            "type": "string",
            "description": "The second line of the address. Typically the number of the apartment, suite, or unit.",
            "nullable": true,
            "example": "123"
          },
          "postal_code": {
            "type": "string",
            "description": "The postal code for the address.",
            "nullable": true,
            "example": "50668"
          },
          "city": {
            "type": "string",
            "description": "The name of the city, district, village, or town.",
            "nullable": true,
            "example": "Cologne"
          },
          "country": {
            "type": "string",
            "description": "The two-letter code for the country of the address.",
            "nullable": true,
            "example": "DE"
          },
          "additional_info": {
            "type": "string",
            "description": "An additional description for the address",
            "nullable": true
          },
          "company_name": {
            "type": "string",
            "description": "the company name, usually used as extra delivery instructions",
            "nullable": true
          },
          "first_name": {
            "type": "string",
            "description": "the first name of the recipient, usually used as extra delivery instructions",
            "nullable": true
          },
          "last_name": {
            "type": "string",
            "description": "the last name of the recipient, usually used as extra delivery instructions",
            "nullable": true
          },
          "salutation": {
            "type": "string",
            "description": "the salutation of the recipient, usually used as extra delivery instructions",
            "nullable": true
          },
          "title": {
            "type": "string",
            "description": "the title of the recipient, usually used as extra delivery instructions",
            "nullable": true
          },
          "coordinates": {
            "type": "string",
            "description": "Geographical coordinates (latitude, longitude)",
            "nullable": true,
            "example": "50.948484, 6.943147"
          },
          "plot_of_land": {
            "type": "string",
            "description": "Plot of land information",
            "nullable": true
          },
          "plot_area": {
            "type": "string",
            "description": "Area of the plot",
            "nullable": true
          },
          "start_date": {
            "type": "string",
            "description": "Start date for the address",
            "format": "date",
            "nullable": true
          },
          "end_date": {
            "type": "string",
            "description": "End date for the address",
            "format": "date",
            "nullable": true
          }
        }
      },
      "description": "Address"
    },
    "activity_radius": {
      "type": "string",
      "description": "Activity Radius (km)"
    },
    "customer": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Customer"
    },
    "email": {
      "type": "string",
      "format": "email",
      "description": "Email"
    },
    "phone": {
      "type": "string",
      "example": "+491234567890",
      "description": "Phone"
    },
    "_availability_files": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Availability File"
    },
    "workflows": {
      "$ref": "#/definitions/WorkflowOverview"
    },
    "_files": {
      "$ref": "#/definitions/BaseRelation"
    },
    "_created_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity creation"
    },
    "_updated_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity last update"
    },
    "_owners": {
      "type": "array",
      "readOnly": true,
      "items": {
        "description": "The user / organization owning this entity.\n\nNote: Owner implicitly has access to the entity regardless of ACLs.\n",
        "type": "object",
        "properties": {
          "org_id": {
            "type": "string",
            "example": "123"
          },
          "user_id": {
            "type": "string",
            "example": "456"
          }
        },
        "required": [
          "org_id"
        ]
      }
    },
    "_acl": {
      "readOnly": true,
      "type": "object",
      "description": "Access control list (ACL) for an entity. Defines sharing access to external orgs or users.",
      "additionalProperties": true,
      "properties": {
        "view": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "edit": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "delete": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        }
      }
    },
    "_manifest": {
      "readOnly": true,
      "type": "array",
      "nullable": true,
      "description": "Blueprint ID used to create/update the entity",
      "items": {
        "type": "string"
      },
      "example": [
        "123e4567-e89b-12d3-a456-426614174000"
      ]
    }
  },
  "definitions": {
    "PurposeAttribute": {
      "type": "array",
      "description": "List of purpose ids",
      "items": {
        "type": "string"
      },
      "example": [
        "7675dc56-fd1b-46ee-9c35-defe0667b32e"
      ]
    },
    "BaseUUID": {
      "type": "string",
      "format": "uuid",
      "example": "123e4567-e89b-12d3-a456-426614174000"
    },
    "BaseTags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "example"
      ]
    },
    "BaseRelation": {
      "type": "object",
      "nullable": true,
      "description": "Relation to another entity",
      "properties": {
        "$relation": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "entity_id": {
                "$ref": "#/definitions/BaseUUID"
              },
              "_tags": {
                "$ref": "#/definitions/BaseTags"
              }
            }
          }
        }
      }
    },
    "WorkflowStatus": {
      "type": "string",
      "enum": [
        "STARTED",
        "DONE",
        "CLOSED"
      ]
    },
    "StepType": {
      "type": "string",
      "enum": [
        "MANUAL",
        "AUTOMATION"
      ]
    },
    "StepStatus": {
      "type": "string",
      "enum": [
        "UNASSIGNED",
        "ASSIGNED",
        "COMPLETED",
        "SKIPPED",
        "IN_PROGRESS"
      ]
    },
    "PhaseInEntity": {
      "type": "object",
      "description": "Workflow phase information",
      "properties": {
        "phase_id": {
          "type": "string"
        },
        "phase_name": {
          "type": "string"
        },
        "phase_progress": {
          "type": "number"
        }
      },
      "required": [
        "phase_id",
        "phase_name",
        "phase_progress"
      ]
    },
    "WorkflowInEntity": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "definition_id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/WorkflowStatus"
        },
        "assignees": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "progress": {
          "type": "number"
        },
        "phases_in_progress": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PhaseInEntity"
          }
        },
        "last_update_time": {
          "type": "string",
          "format": "date-time"
        },
        "upcoming_tasks_assignees": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "task_id": {
          "type": "string"
        },
        "task_name": {
          "type": "string"
        },
        "task_assignees": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "task_duedate": {
          "type": "string",
          "format": "date-time"
        },
        "task_execution_type": {
          "$ref": "#/definitions/StepType"
        },
        "task_status": {
          "$ref": "#/definitions/StepStatus"
        },
        "phase_id": {
          "type": "string"
        },
        "phase_name": {
          "type": "string"
        },
        "phase_assignees": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "phase_progress": {
          "type": "number"
        }
      },
      "required": [
        "id",
        "definition_id",
        "name",
        "status",
        "assignees",
        "last_update_time"
      ]
    },
    "WorkflowOverview": {
      "type": "object",
      "properties": {
        "primary": {
          "$ref": "#/definitions/WorkflowInEntity"
        }
      },
      "additionalProperties": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/WorkflowInEntity"
        }
      }
    }
  }
}

=== epilot-dev/docs/static/schemas/partner-example.json
{
  "_schema": "partner",
  "_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "_org": "123",
  "_title": "John Doe",
  "_tags": [
    "family:label"
  ],
  "_purpose": [
    "7675dc56-fd1b-46ee-9c35-defe0667b32e"
  ],
  "status": "string",
  "company_name_title": "string",
  "description": "string",
  "address": [
    {
      "_tags": [
        "billing"
      ],
      "street": "Hauptstra√üe",
      "street_number": "123",
      "postal_code": "50668",
      "city": "Cologne",
      "country": "DE",
      "additional_info": "string",
      "company_name": "string",
      "first_name": "string",
      "last_name": "string",
      "salutation": "string",
      "title": "string",
      "coordinates": "50.948484, 6.943147",
      "plot_of_land": "string",
      "plot_area": "string",
      "start_date": "string",
      "end_date": "string"
    }
  ],
  "activity_radius": "string",
  "customer": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "email": "user@example.com",
  "phone": "+491234567890",
  "_availability_files": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "workflows": {
    "primary": {
      "id": "string",
      "definition_id": "string",
      "name": "string",
      "status": "STARTED",
      "assignees": [
        "string"
      ],
      "progress": 0,
      "phases_in_progress": [
        {
          "phase_id": "string",
          "phase_name": "string",
          "phase_progress": 0
        }
      ],
      "last_update_time": "1970-01-01T00:00:00.000Z",
      "upcoming_tasks_assignees": [
        "string"
      ],
      "task_id": "string",
      "task_name": "string",
      "task_assignees": [
        "string"
      ],
      "task_duedate": "1970-01-01T00:00:00.000Z",
      "task_execution_type": "MANUAL",
      "task_status": "UNASSIGNED",
      "phase_id": "string",
      "phase_name": "string",
      "phase_assignees": [
        "string"
      ],
      "phase_progress": 0
    }
  },
  "_files": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "_created_at": "1970-01-01T00:00:00.000Z",
  "_updated_at": "1970-01-01T00:00:00.000Z",
  "_owners": [
    {
      "org_id": "123",
      "user_id": "456"
    }
  ],
  "_acl": {
    "view": [
      "org:456"
    ],
    "edit": [
      "org:456"
    ],
    "delete": [
      "org:456"
    ]
  },
  "_manifest": [
    "123e4567-e89b-12d3-a456-426614174000"
  ]
}
